name: Jonnitto
favicon: null
layout_spectrum: 0.8391432163771242
title: Jonnitto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: d600c5dc-78a1-4ebd-80eb-6ddd1f829005
    url: null
typography_spectrum: 0.87593342224136
